export const HIGH_RISK_PATH_PATTERNS: readonly string[] = [
  'infra/**',
  'terraform/**',
  'k8s/**',
  'helm/**',
  'migrations/**',
  'auth/**',
  'payments/**',
  'security/**',
  'secrets/**',
  '.github/workflows/**',
  '.gitlab-ci.yml',
  'Jenkinsfile',
  'AGENTS.md',
  'CLAUDE.md',
  '.codex/**',
  '.claude/**',
  '.mcp.json',
  'package.json',
  'pnpm-lock.yaml',
  'requirements.txt',
] as const;

export const AGENT_POLICY_FILES: readonly string[] = [
  'AGENTS.md',
  'AGENTS.override.md',
  'CLAUDE.md',
  'CLAUDE.local.md',
  '.codex/config.toml',
  '.codex/hooks.json',
  '.claude/settings.json',
  '.claude/settings.local.json',
  '.mcp.json',
] as const;
